module.exports = {
  defineTemplateBodyVisitor: require("./utils/defineTemplateBodyVisitor"),
  getAttributeName: require("./utils/getAttributeName"),
  getAttributeValue: require("./utils/getAttributeValue"),
  getElementAttribute: require("./utils/getElementAttribute"),
  getElementAttributeValue: require("./utils/getElementAttributeValue"),
  getElementType: require("./utils/getElementType"),
  getLiteralAttributeValue: require("./utils/getLiteralAttributeValue"),
  hasAccessibleChild: require("./utils/hasAccessibleChild"),
  hasAriaLabel: require("./utils/hasAriaLabel"),
  hasContent: require("./utils/hasContent"),
  hasOnDirective: require("./utils/hasOnDirective"),
  hasOnDirectives: require("./utils/hasOnDirectives"),
  isAttribute: require("./utils/isAttribute"),
  isHiddenFromScreenReader: require("./utils/isHiddenFromScreenReader"),
  isInteractiveElement: require("./utils/isInteractiveElement"),
  isPresentationRole: require("./utils/isPresentationRole"),
  makeDocsURL: require("./utils/makeDocsURL"),
  makeKebabCase: require("./utils/makeKebabCase"),
  matchesElementRole: require("./utils/matchesElementRole")
};
